version: 2.1

jobs:
  # build:
  #   docker:
  #     - image: cimg/node:18.16.1
  #   steps:
  #     - checkout
  #     - run: yarn
  api_integration_tests_job:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: yarn
      - run: yarn run lint
      - run: cd services/api && yarn run test:unit
      - run: docker-compose up -d postgresdb_test && sleep 2
      - run: cd services/api && yarn run test:integration


workflows:
  api_integration_tests:
    jobs:
      # - build
      - api_integration_tests_job
