version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - run: npm install
  api_integration_tests_job:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - run: npm run lint


workflows:
  api_integration_tests:
    jobs:
      - build
      - api_integration_tests_job
      