
version: 2.1
jobs:
  api-test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Api tests
          command: |
            cd services/api
            npm run test:all
  
  web-test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Web tests
          command: |
            cd services/web
            yarn run test
  
  cypress-test:
    docker:
      - image: cimg/base:2021.04
      steps:
        - run:
            name: Cypress tests
            command: |
              cd services/web
              yarn run start
              cd ../..
              yarn run e2e:run
