version: 2.1

jobs:
  # build:
  #   docker:
  #     - image: cimg/node:18.16.1
  #   steps:
  #     - checkout
  #     - run: yarn
  api_integration_tests_job:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: yarn
      - run: yarn run lint
      - run: cd services/api && yarn run test:unit
      - run: docker-compose up -d postgresdb_test && sleep 2
      - run: export POSTGRES_CONTAINER_ID=$(docker ps | grep postgres:14 | head -n 1 | awk '{print $1;}')
      - run: export POSTGRES_HOSTNAME=$(docker inspect "$POSTGRES_CONTAINER_ID" | jq -r '.[0].Config.Hostname')
      - run: export TEST_DATABASE_URL="postgres://user:pass@$POSTGRES_HOSTNAME:5432/launchpad_test"
      - run: cd services/api && yarn run test:integration


workflows:
  api_integration_tests:
    jobs:
      # - build
      - api_integration_tests_job
