FROM node:16-alpine as builder
WORKDIR /usr/src/app

COPY package.json yarn.lock ./

COPY ./services/api/package.json ./services/api/package.json
COPY packages/shared-types/package.json ./packages/shared-types/package.json

RUN yarn

COPY ./services/api ./services/api
COPY packages/shared-types ./packages/shared-types

WORKDIR /usr/src/app/services/api

RUN npm run build

# FROM node:16-alpine

# WORKDIR /usr/src/app

# COPY --from=builder /usr/src/app/services/api/node_modules ./node_modules
# COPY --from=builder /usr/src/app/services/api/build .
EXPOSE 4000
ENV PORT 4000

CMD [ "yarn", "start" ]
