FROM node:16-alpine as builder

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

COPY ./services/web/package.json ./services/web/package.json
COPY ./packages/shared-types/package.json ./packages/shared-types/package.json

RUN yarn

COPY services/web ./services/web
COPY packages/shared-types ./packages/shared-types

WORKDIR /usr/src/app/services/web

RUN yarn build

FROM nginx:alpine

WORKDIR /var/www/app

COPY stacks/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/services/web/build .

RUN apk add --upgrade apk-tools
RUN apk add --upgrade curl
RUN apk add --upgrade libcurl
RUN apk add --upgrade libxml2
RUN apk add --upgrade libgcrypt
RUN apk add --upgrade libjpeg-turbo

# ARG BASIC_AUTH_HTPASSWD
# RUN echo $BASIC_AUTH_HTPASSWD > /etc/nginx/.htpasswd

EXPOSE 8080

CMD nginx -g "daemon off;"
