FROM node:16-alpine
WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

COPY ./services/api/package.json ./services/api/package.json

RUN yarn install

COPY ./services/api ./services/api

EXPOSE 4000
ENV PORT 4000

CMD [ "yarn", "start:api" ]
